# Imagem base
FROM python3

# Mantenedor do projeto - Troque pelo seu nome e email
LABEL maintainer="Romario Santos sromario577@gmail.com"

# Diretório do projeto
WORKDIR /app

# Copia o arquivo de app
COPY ./app.py /app/app.py

# Copia o arquivo de instalação dos pacotes
COPY ./requirements.txt /app/requirements.txt

# Instala o pacote
RUN pip install -r requirements.txt

# Incia o projeto
CMD [ "python", "app.py" ]