version: '3.8'
services:
  server:
    build: ./server
    container_name: ${SERVER_CONTAINER_NAME}
    ports:
      - ${SERVER_PORT}
    volumes:
      - ./server:/app
    restart: always
    depends_on:
      - db
  client:
    build: ./client
    container_name: ${CLIENT_CONTAINER_NAME}
    ports:
      - ${CLIENT_PORT}
    volumes:
      - ./client:/app
    restart: always
    depends_on:
      - server
      - db
  db:
    image: ${DATABASE_IMAGE}
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - ${DATABASE_PORT}